apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.3333333333333333
    profile: false
    max_hamming: 0

    detector:
      threads: 2
      decimate: 1.0

    tag:
      ids: [10, 11, 12, 13, 20]
      frames:
        - field_tag_10
        - field_tag_11
        - field_tag_12
        - field_tag_13
        - robot_tag_20
      sizes:
        - 0.3333333333333333
        - 0.3333333333333333
        - 0.3333333333333333
        - 0.3333333333333333
        - 0.40
