bno085:
  ros__parameters:
    frame_id: imu_link
    i2c_bus: 1
    publish_rate_hz: 30.0
    report_interval_us:  33333  # 30 Hz
    use_game_rotation_vector: true
    enable_gyroscope: false
    enable_linear_acceleration: false
    orientation_covariance_diagonal: [0.05, 0.05, 0.08]
    angular_velocity_covariance_diagonal: [0.02, 0.02, 0.04]
    linear_acceleration_covariance_diagonal: [0.2, 0.2, 0.3]
