overhead_apriltag_odom:
  ros__parameters:
    detections_topic: /overhead/tag_detections
    odom_topic: /overhead/odom
    pose_topic: /overhead/pose
    pose2d_topic: /overhead/pose2d
    publish_pose: true
    publish_pose2d: true
    field_frame_id: odom
    child_frame_id: base_link
    robot_tag_frame_id: robot_tag_20
    publish_robot_tag_tf: true

    robot_tag_id: 20
    field_tag_ids: [10, 11, 12, 13]
    field_tag_x: [-2.35, 2.35, 2.35, -2.35]
    field_tag_y: [-1.10, -1.10, 1.10, 1.10]

    robot_yaw_offset_rad: 0.0
    position_variance: 0.0004
    yaw_variance: 0.0025
    warn_period_s: 2.0
