mega_driver:
  swap_sides: false
  left_cmd_sign: 1
  right_cmd_sign: 1
  angular_cmd_sign: -1
  min_nonzero_pwm: 50
  min_forward_pwm: 50
  min_reverse_pwm: 60
  min_turn_pwm: 90
  pure_rotation_linear_deadband_mps: 0.0
  left_cmd_scale: 0.96
  right_cmd_scale: 1.0
  left_tick_sign: 1
  right_tick_sign: 1
  left_m_per_tick: 0.000054145
  right_m_per_tick: 0.000053178
  track_width_eff_m: 0.289845896
